### ISSUE TITLE
not able to display Chinese?

### ISSUE THREAD

**Issue by njalan** [vanna-ai/vanna#255]
Why try to display the  column which contains Chinese I got below error:
Traceback (most recent call last):
  File "/Users/xx/anaconda3/envs/vanna/lib/python3.9/site-packages/vanna/flask.py", line 226, in generate_plotly_figure
    fig = vn.get_plotly_figure(plotly_code=code, df=df, dark_mode=False)
  File "/Users/zhujin/anaconda3/envs/vanna/lib/python3.9/site-packages/vanna/base/base.py", line 1317, in get_plotly_figure
    elif len(categorical_cols) >= 1 and df[categorical_cols[0]].nunique() < 10:
  File "/Users/xx/anaconda3/envs/vanna/lib/python3.9/site-packages/pandas/core/base.py", line 1063, in nunique
    uniqs = self.unique()
  File "/Users/xx/anaconda3/envs/vanna/lib/python3.9/site-packages/pandas/core/series.py", line 2397, in unique
    return super().unique()
  File "/Users/xx/anaconda3/envs/vanna/lib/python3.9/site-packages/pandas/core/base.py", line 1025, in unique
    result = algorithms.unique1d(values)
  File "/Users/xx/anaconda3/envs/vanna/lib/python3.9/site-packages/pandas/core/algorithms.py", line 401, in unique
    return unique_with_mask(values)
  File "/Users/xx/anaconda3/envs/vanna/lib/python3.9/site-packages/pandas/core/algorithms.py", line 440, in unique_with_mask
    uniques = table.unique(values)
  File "pandas/_libs/hashtable_class_helper.pxi", line 7248, in pandas._libs.hashtable.PyObjectHashTable.unique
  File "pandas/_libs/hashtable_class_helper.pxi", line 7195, in pandas._libs.hashtable.PyObjectHashTable._unique
TypeError: unhashable type: 'bytearray'

**Comment by zainhoda** [comment]
@njalan what version of Vanna do you have installed? I thought we had fixed this issue a few releases ago

**Comment by njalan** [comment]
@zainhoda  I am using  0.1.0

**Comment by njalan** [comment]
@zainhoda I upgrade to 0.11.0 and then Found that for column in mysql as varchar it shows [object Object] on the web ui. Is there any additional config for it?
