### ISSUE TITLE
Fail to integration with llama.cpp

### ISSUE THREAD

**Issue by njalan** [vanna-ai/vanna#373]
I tried to set openai_api_base as the API started by llama.ccp OpenAI API compatible HTTP server.  vanna is 4.0 and I got below error message:
[2024-04-18 09:33:46,695] ERROR in app: Exception on /api/v0/generate_sql [GET]
Traceback (most recent call last):
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/vanna/flask/__init__.py", line 130, in decorated
    return f(*args, user=user, **kwargs)
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/vanna/flask/__init__.py", line 307, in generate_sql
    sql = vn.generate_sql(question=question)
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/vanna/base/base.py", line 122, in generate_sql
    llm_response = self.submit_prompt(prompt, **kwargs)
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/vanna/openai/openai_chat.py", line 123, in submit_prompt
    response = self.client.chat.completions.create(
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/openai/_base_client.py", line 1213, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/openai/_base_client.py", line 902, in request
    return self._request(
  File "/home/hadoop/.conda/envs/vanna2/lib/python3.9/site-packages/openai/_base_client.py", line 993, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': 404, 'message': 'File Not Found', 'type': 'not_found_error'}}

**Comment by zainhoda** [comment]
This is a 404 error that originates from within the `openai`package. You should first verify that you're able to use the OpenAI client directly to perform chat.completions.create
