### ISSUE TITLE
Adapt the get_training_plan_generic method for Oracle Database

### ISSUE THREAD

**Issue by rmendesl** [vanna-ai/vanna#482]
The `get_training_plan_generic` method does not work for Oracle Database. Because in the Oracle Database there is no INFORMATION_SCHEMA like MySQL or SQL Server. 

It uses other views like ALL_TAB_COLUMNS or USER_TAB_COLUMNS that contain the same information like TABLE_NAME, COLUMN_NAME, DATA_TYPE, DATA_LENGTH, DATA_PRECISION, DATA_SCALE, NULLABLE, COLUMN_ID, etc. 

I would like to suggest adapting this method to the Oracle database.

Error:

```
df_information_schema = vn.run_sql("SELECT * FROM USER_TAB_COLUMNS")

Traceback (most recent call last):
  File "c:\Projects\Python\sonora.ai3\app.py", line 40, in <module>
    training()
  File "c:\Projects\Python\sonora.ai3\app.py", line 30, in training
    plan = vn.get_training_plan_generic(df_information_schema)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Projects\Python\sonora.ai3\sonora_env\Lib\site-packages\vanna\base\base.py", line 1794, in get_training_plan_generic
    database_column = df.columns[
                      ^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by PucaVaz** [comment]
Can you use something like```
 SELECT VIEW_NAME, TEXT
FROM ALL_VIEWS
WHERE OWNER = 'owner' AND VIEW_NAME = 'name';? 
```  If you run with vn.runsql() will return a pd data frame, so you can adjust a little bitter to work

**Comment by rmendesl** [comment]
@gregholliday I did the process you mentioned and it apparently worked.

**Comment by maniteja-kamsali** [comment]
df_information_schema = vn.run_sql("""
SELECT 
    OWNER AS table_schema,
    TABLE_NAME AS table_name,
    COLUMN_NAME AS column_name,
    DATA_TYPE AS data_type,
    DATA_LENGTH AS character_maximum_length,
    DATA_PRECISION AS numeric_precision,
    DATA_SCALE AS numeric_scale,
    NULLABLE AS is_nullable
FROM 
    ALL_TAB_COLUMNS
WHERE 
    OWNER = 'BIUSR'
    AND TABLE_NAME LIKE 'TBL_TRN%'
ORDER BY 
    TABLE_NAME, COLUMN_ID
""") im using the same process but throwing me the same error   
plan = vn.get_training_plan_generic(df_information_schema)
IndexError: list index out of range

**Comment by PucaVaz** [comment]
@maniteja-kamsali you can try to write your own get_training_plan, is not that hard, look for the code for the generic at base.py
