### ISSUE TITLE
Ask same QUESTION at Training Data return error

### ISSUE THREAD

**Issue by lokwingfai** [vanna-ai/vanna#551]
**Describe the bug**
Ask same QUESTION at Training Data return error

**To Reproduce**
1. Go to 'Training Data'
2. Copy one of the 'QUESTION'
3. Click on 'New question'
4. Paste the copied 'QUESTION'
6. See error

**Expected behavior**
same answer at 'Training Data''s 'CONTENT'

**Error logs/Screenshots**
<img width="1280" alt="Screenshot 2024-07-12 at 4 50 48 PM" src="https://github.com/user-attachments/assets/c4e7eb0d-05bc-4ff8-bfaa-b978dde2c2b4">
<img width="1280" alt="Screenshot 2024-07-12 at 4 57 47 PM" src="https://github.com/user-attachments/assets/c1f3ba8e-ec13-4802-86ef-a24f270aed19">

//--{{ START
Add of existing embedding ID: ac76c4eb-7236-546c-a7a6-612e4348d86c-sql
Number of requested results 10 is greater than number of elements in index 0, updating n_results = 0
Add of existing embedding ID: 891217d9-8a47-5ca6-8c19-ca63e07630f6-doc
Add of existing embedding ID: 0041f745-8ec9-5534-a2cf-7151fa37c85e-doc
Add of existing embedding ID: 4fa28928-77de-5a38-85f3-418e79aaa1b5-doc
Add of existing embedding ID: e94202bf-f54f-5eaf-8df1-f36bcb56e6b1-doc
Number of requested results 10 is greater than number of elements in index 3, updating n_results = 3
Number of requested results 10 is greater than number of elements in index 0, updating n_results = 0
Number of requested results 10 is greater than number of elements in index 3, updating n_results = 3
Traceback (most recent call last):
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 124, in read
    with map_exceptions(exc_map):
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/flask/app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/flask/app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/vanna/flask/__init__.py", line 134, in decorated
    return f(*args, user=user, **kwargs)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/vanna/flask/__init__.py", line 336, in generate_sql
    sql = vn.generate_sql(question=question, allow_llm_to_see_data=self.allow_llm_to_see_data)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/vanna/base/base.py", line 136, in generate_sql
    llm_response = self.submit_prompt(prompt, **kwargs)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/vanna/ollama/ollama.py", line 93, in submit_prompt
    response_dict = self.ollama_client.chat(model=self.model,
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/ollama/_client.py", line 180, in chat
    return self._request_stream(
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/ollama/_client.py", line 98, in _request_stream
    return self._stream(*args, **kwargs) if stream else self._request(*args, **kwargs).json()
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/ollama/_client.py", line 69, in _request
    response = self._client.request(method, url, **kwargs)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/ollama/master-vanna-sql-server/.venv-sql-server/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: timed out
//--}} END

**Desktop (please complete the following information where):**
 - OS: [Ubuntu]
 - Version: [22.04.4 LTS]
 - Python: [3.10.12]
 - Vanna: [2.8.0]

**Comment by andyops** [comment]
Cannot Reproduce it

**Comment by RickyAllen00** [comment]
have you fix this bug? I meet same problem here

**Comment by lokwingfai** [comment]
> have you fix this bug? I meet same problem here
no, I don't find any way to fix it.

**Comment by Daniel07n** [comment]
Same here, Vanna 0.75, ChromaDB, Ollama with "mradermacher/openbuddy-codellama-70b-v17.1-4k-GGUF:Q4_K_M" on an MacBook M3 Max, 128GB RAM.

**Comment by pocupine** [comment]
After hours of trying, I found Vanna default flask backend process the questions as below:
Input question --> interpret question (likely LLM processed especially starting from the 2nd question ) --> SQL
For me, this process is not logical. It should compare with the trained data for exact match first, if not found, then do as the above.
For this reason, if you want it work the way I wanted, you have to make your own Flask web page.
