### ISSUE TITLE
where could I get the source code of vanna-flask ?

### ISSUE THREAD

**Issue by QuintinTao** [vanna-ai/vanna#733]
where could I get the source code of vanna-flask ?         I want to revise the web page of the vanna-flask

**Comment by zifeiYv** [comment]
https://github.com/vanna-ai/vanna-flask

**Comment by azawalich** [comment]
@zifeiYv the above is no longer mantained. @QuintinTao you can check out the flask part of the source code: https://github.com/vanna-ai/vanna/tree/main/src/vanna/flask. If you need to overwrite it, it is possible.

**Comment by jeroenvds** [comment]
Is the original source code for the Assets available anywhere? See discussion https://github.com/vanna-ai/vanna/discussions/515 : Only a minified version of the JS and CSS is available in the current git repository. Thanks!

**Comment by azawalich** [comment]
@jeroenvds see my comment above
-----
Wysłane z urządzenia mobilnego.
Sent from a mobile device.
Pozdrowienia / Greetings
Aleksander Zawalich
https://zawalich.pl

pon., 17 lut 2025, 10:18 użytkownik jeroenvds ***@***.***>
napisał:

**Comment by jeroenvds** [comment]
Thanks @azawalich , but if you look in the assets.py file, you'll see that the js_content and css_content strings are impossible to maintain in the current form. This is clearly minified code, which can't be easily interpreted by a human. Of course you can try to reverse engineer, but that's less efficient.

**Comment by szcc** [comment]
I am running the vanna in a docker container. I got error from js file. 
"Uncaught TypeError: Cannot read properties of undefined (reading '$$')
    at $e (index-d29524f4.js:1:4869)
    at new Oi (index-d29524f4.js:13:12789)
    at index-d29524f4.js:13:12813"/
The js file "index-d29524f4.js:" is provided by vanna. How can I solve this problem? 
Thanks a lot,
